/**
 * Renders carta.html from assets/data/menu.json.
 *
 * Edit the JSON when the menu changes, then run:  node tools/build-carta.js
 * carta.html is committed output — don't hand-edit it, your changes get overwritten.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const menu = JSON.parse(fs.readFileSync(path.join(root, 'assets/data/menu.json'), 'utf8'));

const esc = (s) =>
  String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

// Numeric prices get the serif treatment; "Consultar" and friends stay in the sans face.
const isAmount = (price) => /\d/.test(price);

function renderDish(dish) {
  const flags = [
    dish.glutenFree ? '<span class="dish__flag">(SG)</span>' : '',
    dish.recommended ? '<span class="dish__flag dish__flag--rec">· Recomendado</span>' : '',
  ]
    .filter(Boolean)
    .join(' ');

  const priceClass = isAmount(dish.price) ? 'dish__price' : 'dish__price dish__price--text';
  const desc = dish.description ? `\n        <p class="dish__desc">${esc(dish.description)}</p>` : '';

  return `      <div class="dish">
        <div class="dish__row">
          <span class="dish__name">${esc(dish.name)}${flags ? ' ' + flags : ''}</span>
          <span class="dish__leader"></span>
          <span class="${priceClass}">${esc(dish.price)}</span>
        </div>${desc}
      </div>`;
}

function renderCourse(course) {
  return `  <section class="course" id="${esc(course.id)}">
    <div class="course__head">
      <span class="course__kicker">${esc(course.kicker)}</span>
      <div class="course__title-row">
        <span class="rule"></span>
        <h2>${esc(course.title)}</h2>
        <span class="rule"></span>
      </div>
    </div>
    <div class="dishes">
${course.items.map(renderDish).join('\n')}
    </div>
  </section>`;
}

const page = `<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>La Carta — TJ · La Taberna del Herrero</title>
<meta name="description" content="Carta de TJ · La Taberna del Herrero en Yecla: aperitivos, marisco, carnes y pescados a la brasa, postres y bebidas.">
<link rel="icon" href="assets/img/tj-mark-cream.png">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Inter:ital,opsz,wght@0,14..32,100..900;1,14..32,100..900&family=Syne:wght@400..800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="assets/css/site.css">
</head>
<body>

<!-- Generated by tools/build-carta.js from assets/data/menu.json — do not edit by hand. -->

<header class="site-header">
  <a class="brand" href="index.html">
    <img src="assets/img/tj-mark-cream.png" alt="">
    <span>TJ · La Taberna del Herrero</span>
  </a>

  <nav class="nav">
    <a href="index.html">Inicio</a>
    <a href="carta.html" aria-current="page">Carta</a>
    <a href="nosotros.html">Nosotros</a>
    <a class="nav-cta" href="contacto.html">Reservar</a>
  </nav>

  <button class="nav-toggle" type="button" aria-label="Abrir menú" aria-expanded="false" aria-controls="nav-mobile">
    <span></span>
    <span></span>
  </button>

  <div class="nav-mobile" id="nav-mobile">
    <a href="index.html">Inicio</a>
    <a href="carta.html" aria-current="page">Carta</a>
    <a href="nosotros.html">Nosotros</a>
    <a class="nav-cta" href="contacto.html">Reservar</a>
  </div>
</header>

<div class="page-hero page-hero--short">
  <img src="assets/img/tosta-anchoas.png" alt="Tosta de anchoas">
  <div class="page-hero__scrim"></div>
  <div class="page-hero__inner">
    <span class="page-hero__eyebrow">Producto de mercado</span>
    <h1>La Carta</h1>
  </div>
</div>

<div class="menu-intro">
  <p>Cocina de mercado con producto fresco de lonja y huerta, cocinado a la brasa. (SG) indica opción sin gluten disponible bajo petición. Precios en euros, IVA incluido.</p>
</div>

<main class="menu">
${menu.map(renderCourse).join('\n\n')}
</main>

<footer class="site-footer">
  <div class="site-footer__cols">
    <div class="site-footer__col site-footer__brand">
      <div class="site-footer__mark">
        <img src="assets/img/tj-mark-cream.png" alt="">
        <span>La Taberna del Herrero</span>
      </div>
      <p>Terraza · Chimenea · Comedor privado</p>
      <a class="site-footer__social" href="https://www.instagram.com/tjlatabernadelherrero/" target="_blank" rel="noopener">Instagram ↗</a>
    </div>

    <div class="site-footer__col">
      <span class="site-footer__label">Dirección</span>
      <span>Av. Literato Azorín, 8<br>30510 Yecla, Murcia</span>
      <a href="tel:+34611510550">611 51 05 50</a>
    </div>

    <div class="site-footer__col site-footer__col--hours">
      <span class="site-footer__label">Horario</span>
      <span>Mié · Jue · Vie · Sáb 13:30–1:00<br>Domingo 13:30–24:00<br>Lunes y martes cerrado</span>
    </div>

    <div class="site-footer__col">
      <span class="site-footer__label">Visítanos</span>
      <a class="btn" href="contacto.html">Cómo llegar</a>
    </div>
  </div>

  <div class="site-footer__legal">
    <span>© 2026 La Taberna del Herrero</span>
    <span>Yecla, Murcia</span>
  </div>
</footer>

<script src="assets/js/site.js"></script>
</body>
</html>
`;

fs.writeFileSync(path.join(root, 'carta.html'), page, 'utf8');
console.log(
  `carta.html — ${menu.length} secciones, ${menu.reduce((n, s) => n + s.items.length, 0)} platos`
);
